### ISSUE TITLE
Bug: local etc/hosts not adjusted by `vagrant provision`

### ISSUE THREAD

**Issue by rnarian** [frdmn/servant#15]
When following the installation guide, after running `vagrant provision` demoproject.io isn't added to local `/etc/hosts`.

**Comment by frdmn** [comment]
Known issue, apparently:

devopsgroup-io/vagrant-hostmanager#56

We need to find an alternative.

**Comment by frdmn** [comment]
Known issue, apparently:

devopsgroup-io/vagrant-hostmanager#159

We need to find an alternative.

**Comment by frdmn** [comment]
Fixed in 61ff4ee32b32f28eddb7db8d1294f48697773ae3
